[package]
name = "ferrite"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
makefile-lossless = "0.1.7"
ratatui = { version = "0.29.0", features = ["macros"] }
tempfile = "3.15.0"
widgetui = "0.7.1"
